recipes:
{% if build_type == 'cuda' and cudatoolkit == '11.2' %}
  - name : pytorch-select
    path : pytorch-1.10/select_recipe

  - name : pytorch-base
    path : pytorch-1.10/recipe

  - name : pytorch-meta
    path : pytorch-1.10/meta_recipe
{% else %}
  - name : pytorch-select
    path : pytorch-1.11/select_recipe

  - name : pytorch-base
    path : pytorch-1.11/recipe

  - name : pytorch-meta
    path : pytorch-1.11/meta_recipe
{% endif %}
